### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by asdrolf** [avafinger/nanopi-a64-kodi#1]
I tried it but i get it not working...
Downloaded the image (https://github.com/avafinger/nanopi-a64-kodi/releases/tag/v1.1
) , and burned it with etcher but its not booting on my nanopia64.

**Comment by avafinger** [comment]
Can you post the complete boot log?

**Comment by asdrolf** [comment]
i dont have hdmi acces i switched to armbian and installed kodi manually
